#!/usr/bin/env bash
#
# Watch With Friends - interactive installer.
# Generates .env, builds the image and starts the stack.
#
set -euo pipefail

cd "$(dirname "$0")"

BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'
YELLOW=$'\033[33m'; BLUE=$'\033[36m'; RESET=$'\033[0m'

say()  { printf '%s\n' "$*"; }
step() { printf '\n%s==>%s %s%s%s\n' "$BLUE" "$RESET" "$BOLD" "$*" "$RESET"; }
ok()   { printf '%s  ok%s %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '%s  !!%s %s\n' "$YELLOW" "$RESET" "$*"; }
die()  { printf '\n%serror:%s %s\n' "$RED" "$RESET" "$*" >&2; exit 1; }

cat <<'BANNER'

  🍿  Watch With Friends - installer
      ---------------------------------

BANNER

# ------------------------------------------------------------------ #
# Requirements                                                        #
# ------------------------------------------------------------------ #

step "Checking requirements"

command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/engine/install/"
docker info >/dev/null 2>&1 || die "Docker is installed but not running (or this user lacks permission - try 'sudo usermod -aG docker \$USER' then log out and back in)."
ok "docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo '')"

if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "Docker Compose is not available. Install the compose plugin: https://docs.docker.com/compose/install/"
fi
ok "compose via '$COMPOSE'"

# ------------------------------------------------------------------ #
# Secret generation                                                   #
# ------------------------------------------------------------------ #

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -d '\n'
  elif [ -r /dev/urandom ]; then
    head -c 48 /dev/urandom | base64 | tr -d '\n'
  else
    die "No way to generate a random secret (need openssl or /dev/urandom)."
  fi
}

# ------------------------------------------------------------------ #
# Existing install?                                                   #
# ------------------------------------------------------------------ #

if [ -f .env ]; then
  step "Found an existing .env"
  say "  This looks like an upgrade rather than a fresh install."
  printf '  Keep the existing configuration? [Y/n] '
  read -r keep < /dev/tty || keep=Y
  case "${keep:-Y}" in
    [nN]*)
      cp .env ".env.backup.$(date +%Y%m%d%H%M%S)"
      ok "backed up the old .env"
      rm -f .env
      ;;
    *)
      ok "keeping your configuration"
      step "Rebuilding and restarting"
      $COMPOSE up -d --build
      ok "done - your data and accounts are untouched"
      exit 0
      ;;
  esac
fi

# ------------------------------------------------------------------ #
# Questions                                                           #
# ------------------------------------------------------------------ #

step "Configuration"
say "${DIM}  Press enter to accept the value in brackets.${RESET}"
say ""

ask() {
  local prompt="$1" default="$2" answer
  printf '  %s [%s]: ' "$prompt" "$default"
  read -r answer < /dev/tty || answer=""
  printf '%s' "${answer:-$default}"
}

ask_secret() {
  local prompt="$1" answer
  printf '  %s: ' "$prompt"
  read -rs answer < /dev/tty || answer=""
  printf '\n'
  printf '%s' "$answer"
}

DOMAIN=$(ask "Public domain (blank = IP access only)" "")
PORT=$(ask "Host port" "8080")
ADMIN_USERNAME=$(ask "Admin username" "admin")

ADMIN_PASSWORD=""
while true; do
  ADMIN_PASSWORD=$(ask_secret "Admin password (blank = generate one)")
  [ -z "$ADMIN_PASSWORD" ] && break
  if [ "${#ADMIN_PASSWORD}" -lt 8 ]; then
    warn "at least 8 characters, please"
    continue
  fi
  CONFIRM=$(ask_secret "Repeat the password")
  [ "$ADMIN_PASSWORD" = "$CONFIRM" ] && break
  warn "those did not match, try again"
done

YOUTUBE_API_KEY=$(ask "YouTube API key (optional, can be added in the UI later)" "")
TZ_VALUE=$(ask "Timezone" "${TZ:-Europe/Berlin}")

# Compose can only mount a named volume it declares, so anything other than the
# built-in "wwf-data" has to be an absolute host path.
while true; do
  DATA_PATH=$(ask "Data directory (absolute host path, or 'volume' for a Docker volume)" "volume")
  case "$DATA_PATH" in
    volume|wwf-data) DATA_PATH="volume"; break ;;
    /*)              break ;;
    *)               warn "give an absolute path starting with / - or 'volume'" ;;
  esac
done

SESSION_SECRET=$(random_secret)

# ------------------------------------------------------------------ #
# Write .env                                                          #
# ------------------------------------------------------------------ #

step "Writing .env"

umask 077
cat > .env <<EOF
# Generated by install.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Keep this file private - it contains your session secret.

SESSION_SECRET=$SESSION_SECRET
ADMIN_USERNAME=$ADMIN_USERNAME
ADMIN_PASSWORD=$ADMIN_PASSWORD
YOUTUBE_API_KEY=$YOUTUBE_API_KEY
TZ=$TZ_VALUE
HOST_PORT=$PORT
PUBLIC_DOMAIN=$DOMAIN
EOF

if [ "$DATA_PATH" != "volume" ]; then
  mkdir -p "$DATA_PATH"
  # The container runs as uid 1000; the data directory must be writable by it.
  if [ "$(id -u)" -eq 0 ]; then
    chown -R 1000:1000 "$DATA_PATH"
    ok "prepared $DATA_PATH (owned by uid 1000)"
  else
    warn "run 'sudo chown -R 1000:1000 $DATA_PATH' if the container cannot write to it"
  fi
  echo "DATA_PATH=$DATA_PATH" >> .env
else
  echo "DATA_PATH=wwf-data" >> .env
fi

chmod 600 .env
ok ".env written (permissions 600)"

# ------------------------------------------------------------------ #
# Build and start                                                     #
# ------------------------------------------------------------------ #

step "Building the image"
say "${DIM}  First build takes a few minutes - it compiles the UI and the native SQLite driver.${RESET}"
$COMPOSE build

step "Starting"
$COMPOSE up -d

step "Waiting for the server to come up"
for i in $(seq 1 60); do
  if curl -sf "http://127.0.0.1:${PORT}/api/health" >/dev/null 2>&1; then
    ok "healthy after ${i}s"
    break
  fi
  if [ "$i" -eq 60 ]; then
    warn "still not responding - check the logs with: $COMPOSE logs -f"
    exit 1
  fi
  sleep 1
done

# ------------------------------------------------------------------ #
# Done                                                                #
# ------------------------------------------------------------------ #

if [ -z "$ADMIN_PASSWORD" ]; then
  GENERATED=$($COMPOSE logs watch-with-friends 2>/dev/null | grep -m1 'password:' | sed 's/.*password: //' | tr -d '\r' || true)
fi

cat <<EOF

${GREEN}${BOLD}  Done. 🎉${RESET}

  ${BOLD}Local${RESET}      http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost'):${PORT}
EOF

if [ -n "$DOMAIN" ]; then
  cat <<EOF
  ${BOLD}Public${RESET}     https://${DOMAIN}
             ${DIM}(point your Cloudflare Tunnel at http://127.0.0.1:${PORT})${RESET}
EOF
fi

cat <<EOF

  ${BOLD}Sign in${RESET}    username: ${ADMIN_USERNAME}
EOF

if [ -n "${GENERATED:-}" ]; then
  printf '             password: %s%s%s  %s(generated - save it now)%s\n' "$BOLD" "$GENERATED" "$RESET" "$DIM" "$RESET"
elif [ -z "$ADMIN_PASSWORD" ]; then
  printf '             password: see  %s logs watch-with-friends\n' "$COMPOSE"
else
  printf '             password: the one you just chose\n'
fi

cat <<EOF

  ${BOLD}Next${RESET}       1. Sign in and change the admin password under Settings
             2. Admin → Codes → generate registration codes for your friends
             3. Send them the sign-up link the panel gives you

  ${DIM}logs:     $COMPOSE logs -f
  stop:     $COMPOSE down
  update:   git pull && ./install.sh${RESET}

EOF
